services:
  db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: database/Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./database/mysql_data:/var/lib/mysql
      - ./database/startup_scripts:/docker-entrypoint-initdb.d
    expose:
      - 3306
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      retries: 30
      start_period: 15s
      timeout: 10s
    ulimits:
      nofile:
        soft: 2100
        hard: 4000
  fast_api:
    command: >
      sh -c "alembic upgrade heads
            cd ../../ 
            gunicorn app.main:app --bind 0.0.0.0:8888 --worker-class uvicorn.workers.UvicornWorker --workers 3 --config ./gunicorn.conf.py"
    depends_on:
      db:
        condition: service_healthy
    container_name: fast_api
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    env_file: .env
    ports:
      - 8888:8888
      
