services:
  db:
    container_name: mysql_db
    build:
      context: .
      dockerfile: database/Dockerfile
    restart: always
    env_file: .env
    volumes:
      - ./database/mysql_data:/var/lib/mysql
      - ./database/startup_scripts:/docker-entrypoint-initdb.d
    expose:
      - 3306
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      retries: 30
      start_period: 15s
      timeout: 10s
  fast_api:
    command: >
      sh -c "alembic upgrade heads
            cd ../../ 
            uvicorn app.main:app --host 0.0.0.0 --port 80"
    depends_on:
      db:
        condition: service_healthy
    container_name: fast_api
    environment:
      - FRONTEND_ADDRESS=${FRONTEND_ADDRESS}
    build:
      context: .
      dockerfile: app/Dockerfile
    restart: always
    env_file: .env
    ports:
      - 80:80
