"""add ListItem to Wallet relationship

Revision ID: 38e7a650866a
Revises: 58e8d2f0bdad
Create Date: 2022-08-09 22:26:58.505247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38e7a650866a'
down_revision = '58e8d2f0bdad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
