"""fix mistaken spell in relationship

Revision ID: 44a85411beed
Revises: bb1e93087bfa
Create Date: 2022-08-10 11:47:57.079940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44a85411beed'
down_revision = 'bb1e93087bfa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
