"""add some relationships

Revision ID: 58e8d2f0bdad
Revises: 926444682485
Create Date: 2022-08-09 22:25:05.360667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e8d2f0bdad'
down_revision = '926444682485'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
