"""change backref to backpopulates

Revision ID: 926444682485
Revises: eae830bdf7fe
Create Date: 2022-08-09 22:20:37.581613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926444682485'
down_revision = 'eae830bdf7fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
