"""add other tables

Revision ID: 9df310e3ab96
Revises: d4046659aef7
Create Date: 2022-08-09 09:41:25.927326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df310e3ab96'
down_revision = 'd4046659aef7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_detail_type',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('list',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('list_type_id', sa.BigInteger(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.Column('signing_pk', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['list_type_id'], ['list_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('list_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('list_id', sa.BigInteger(), nullable=True),
    sa.Column('signed_address', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'list_id', name='unique_lister')
    )
    op.create_table('token_detail',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('token_id', sa.BigInteger(), nullable=True),
    sa.Column('token_detail_type_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['token_detail_type_id'], ['token_detail_type.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_id', 'token_detail_type_id', name='unique_detail')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_detail')
    op.drop_table('list_item')
    op.drop_table('list')
    op.drop_table('token_detail_type')
    op.drop_table('list_type')
    # ### end Alembic commands ###
