"""add list to collection relationship

Revision ID: bb1e93087bfa
Revises: 7cf58e92b979
Create Date: 2022-08-10 08:57:28.509980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb1e93087bfa'
down_revision = '7cf58e92b979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
