"""init

Revision ID: c2351807e53c
Revises: 
Create Date: 2022-08-09 09:20:09.593774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2351807e53c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('token',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dlm', sa.DateTime(), nullable=True),
    sa.Column('time_created', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('nft_id', sa.BigInteger(), nullable=False),
    sa.Column('wallet_id', sa.BigInteger(), nullable=True),
    sa.Column('collection_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    op.drop_table('wallet')
    op.drop_table('collection')
    # ### end Alembic commands ###
